# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 550)
        MainWindow.setMinimumSize(QtCore.QSize(650, 550))
        MainWindow.setMaximumSize(QtCore.QSize(650, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 651, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(55, 55, 75);\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Link_Video_LineEdit = QtWidgets.QLineEdit(self.frame)
        self.Link_Video_LineEdit.setGeometry(QtCore.QRect(40, 80, 421, 31))
        self.Link_Video_LineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(16, 16, 16, 155);\n"
"    border-color: rgb(100, 200, 200);\n"
"    border-color: rgb(0, 153, 255);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(195, 195, 195);\n"
"    font: 57 8pt \"Rubik Medium\";\n"
"    padding-top: 3px;\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"}")
        self.Link_Video_LineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Link_Video_LineEdit.setObjectName("Link_Video_LineEdit")
        self.Check_Video_Button = QtWidgets.QPushButton(self.frame)
        self.Check_Video_Button.setGeometry(QtCore.QRect(470, 80, 101, 31))
        self.Check_Video_Button.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 57 9pt \"Rubik Medium\";\n"
"    background-color: rgb(0, 153, 255);\n"
"}\n"
"\n"
"QPushButton:hover{        \n"
"    background-color: rgb(0, 123, 205);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 85, 110);\n"
"}")
        self.Check_Video_Button.setObjectName("Check_Video_Button")
        self.Autor_Program_Label = QtWidgets.QLabel(self.frame)
        self.Autor_Program_Label.setGeometry(QtCore.QRect(230, 520, 221, 20))
        self.Autor_Program_Label.setStyleSheet("QLabel{\n"
"    font: 57 9pt \"Rubik\";\n"
"    color: rgb(205, 205, 205);\n"
"}")
        self.Autor_Program_Label.setObjectName("Autor_Program_Label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(40, 450, 571, 31))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(124, 113, 116);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 57 10pt \"Rubik Medium\";\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop: 0  rgb(165, 22, 38), stop: 1 rgb(228, 57, 58));\n"
"\n"
"\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.Roll_MinimizeButton = QtWidgets.QPushButton(self.frame)
        self.Roll_MinimizeButton.setGeometry(QtCore.QRect(580, 10, 21, 21))
        self.Roll_MinimizeButton.setStyleSheet("QPushButton{\n"
"    border-radius: 7px;\n"
"    background-color: rgb(100, 150, 255);\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{        \n"
"    background-color: rgb(0, 170, 255);\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(85, 85, 255);\n"
"    padding-top: 5px;\n"
"}")
        self.Roll_MinimizeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menu_ico/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Roll_MinimizeButton.setIcon(icon)
        self.Roll_MinimizeButton.setIconSize(QtCore.QSize(18, 18))
        self.Roll_MinimizeButton.setObjectName("Roll_MinimizeButton")
        self.Close_MinimizeButton = QtWidgets.QPushButton(self.frame)
        self.Close_MinimizeButton.setGeometry(QtCore.QRect(610, 10, 21, 21))
        self.Close_MinimizeButton.setStyleSheet("QPushButton{\n"
"    border-radius: 7px;\n"
"    background-color: rgb(235, 48, 38);\n"
"}\n"
"\n"
"QPushButton:hover{        \n"
"    background-color: rgb(248, 87, 88);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(175, 23, 38);\n"
"}")
        self.Close_MinimizeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/menu_ico/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close_MinimizeButton.setIcon(icon1)
        self.Close_MinimizeButton.setIconSize(QtCore.QSize(18, 18))
        self.Close_MinimizeButton.setObjectName("Close_MinimizeButton")
        self.Progress_Text_Label = QtWidgets.QLabel(self.frame)
        self.Progress_Text_Label.setGeometry(QtCore.QRect(150, 490, 371, 21))
        self.Progress_Text_Label.setStyleSheet("QLabel{\n"
"    font: 57 10pt \"Rubik Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Progress_Text_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Progress_Text_Label.setObjectName("Progress_Text_Label")
        self.Prew_Label = QtWidgets.QLabel(self.frame)
        self.Prew_Label.setGeometry(QtCore.QRect(50, 180, 261, 141))
        self.Prew_Label.setAutoFillBackground(False)
        self.Prew_Label.setStyleSheet("QLabel{\n"
"    background-color: rgba(25, 25, 25, 155);\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.Prew_Label.setText("")
        self.Prew_Label.setTextFormat(QtCore.Qt.AutoText)
        self.Prew_Label.setPixmap(QtGui.QPixmap(":/videologo/video logo.png"))
        self.Prew_Label.setScaledContents(True)
        self.Prew_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Prew_Label.setWordWrap(False)
        self.Prew_Label.setOpenExternalLinks(False)
        self.Prew_Label.setObjectName("Prew_Label")
        self.Video_Info = QtWidgets.QTextEdit(self.frame)
        self.Video_Info.setGeometry(QtCore.QRect(320, 180, 291, 181))
        self.Video_Info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Video_Info.setStyleSheet("QTextEdit{\n"
"    background-color: rgba(16, 16, 16, 155);\n"
"    border-radius: 5px;\n"
"    color: rgb(195, 195, 195);\n"
"    font: 57 9pt \"Rubik Medium\";\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
" {\n"
"     background-color: #2A2929;\n"
"     width: 15px;\n"
"     margin: 15px 3px 15px 3px;\n"
"     border: 1px transparent #2A2929;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color: rgb(157, 208, 255);    \n"
"     min-height: 5px;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;  \n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::add-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;   \n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
" {\n"
"               \n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
" {             \n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }")
        self.Video_Info.setTabChangesFocus(True)
        self.Video_Info.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.Video_Info.setReadOnly(True)
        self.Video_Info.setCursorWidth(1)
        self.Video_Info.setObjectName("Video_Info")
        self.Info_Video_LineEdit = QtWidgets.QLineEdit(self.frame)
        self.Info_Video_LineEdit.setGeometry(QtCore.QRect(40, 130, 581, 241))
        self.Info_Video_LineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border-color: rgb(255, 206, 107);\n"
"    border-color: rgb(67, 127, 191);\n"
"    border-style: solid;\n"
"    border-width: 1.3px;\n"
"    border-radius: 5px;\n"
"    color: rgb(195, 195, 195);\n"
"    font: 57 8pt \"Rubik Medium\";\n"
"    padding-top: 3px;\n"
"    padding-left: 3px;\n"
"    padding-right: 3px;\n"
"}")
        self.Info_Video_LineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Info_Video_LineEdit.setReadOnly(True)
        self.Info_Video_LineEdit.setPlaceholderText("")
        self.Info_Video_LineEdit.setObjectName("Info_Video_LineEdit")
        self.Name_Video = QtWidgets.QLabel(self.frame)
        self.Name_Video.setGeometry(QtCore.QRect(50, 140, 561, 31))
        self.Name_Video.setStatusTip("")
        self.Name_Video.setAccessibleDescription("")
        self.Name_Video.setStyleSheet("QLabel{\n"
"    background-color: rgba(16, 16, 16, 155);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border-radius: 5px;\n"
"    color: rgba(195, 195, 195, 155);\n"
"    font: 57 9pt \"Rubik Medium\";\n"
"}\n"
"")
        self.Name_Video.setScaledContents(True)
        self.Name_Video.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_Video.setObjectName("Name_Video")
        self.ButtonsPanel = QtWidgets.QFrame(self.frame)
        self.ButtonsPanel.setEnabled(True)
        self.ButtonsPanel.setGeometry(QtCore.QRect(10, 409, 631, 111))
        self.ButtonsPanel.setStyleSheet("QFrame{\n"
"        border: 0px solid rgba(0, 0, 0, 0);\n"
"}")
        self.ButtonsPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonsPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonsPanel.setObjectName("ButtonsPanel")
        self.Download_Button = QtWidgets.QPushButton(self.ButtonsPanel)
        self.Download_Button.setGeometry(QtCore.QRect(340, 30, 241, 41))
        self.Download_Button.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 57 12pt \"Rubik Medium\";\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop: 0  rgb(175, 23, 38), stop: 1 rgb(225, 48, 38));\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop: 0  rgb(165, 13, 28), stop: 1 rgb(215, 38, 28));\n"
"}\n"
"\n"
"QPushButton:hover{        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop: 0  rgb(225, 48, 38), stop: 1 rgb(248, 77, 108));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 85, 110);\n"
"}")
        self.Download_Button.setObjectName("Download_Button")
        self.QualityBox = QtWidgets.QComboBox(self.ButtonsPanel)
        self.QualityBox.setGeometry(QtCore.QRect(50, 30, 241, 41))
        self.QualityBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QualityBox.setAutoFillBackground(False)
        self.QualityBox.setStyleSheet("QComboBox{\n"
"    border-radius: 10px;\n"
"    font: 57 14pt \"Rubik Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px sold;\n"
"    padding: 0px 90px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop: 0   rgb(0, 103, 185), stop: 1 rgb(0, 197, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop: 0   rgb(0, 93, 165), stop: 1 rgb(0, 157, 225));\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"   /* border: 2px solid rgb(194, 194, 255);*/\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop: 0  rgb(0, 153, 255), stop: 1 rgb(0, 237, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop: 0  rgb(0, 133, 245), stop: 1 rgb(0, 217, 235));\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid rgb(100, 146, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(0, 0, 0);    \n"
"    background-color: rgb(243, 244, 255);\n"
"    padding: 10px;\n"
"    border: 2px solid rgb(212, 215, 255);\n"
"    border-radius: 10px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    selection-background-color: rgb(140, 146, 255);\n"
"}")
        self.QualityBox.setEditable(False)
        self.QualityBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.QualityBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.QualityBox.setDuplicatesEnabled(False)
        self.QualityBox.setObjectName("QualityBox")
        self.QualityBox.addItem("")
        self.QualityBox.addItem("")
        self.QualityBox.addItem("")
        self.QualityBox.addItem("")
        self.QualityBox.addItem("")
        self.QualityBox.addItem("")
        self.QualityBox.addItem("")
        self.QualityBox.addItem("")
        self.Choose_Folder_Button = QtWidgets.QPushButton(self.frame)
        self.Choose_Folder_Button.setGeometry(QtCore.QRect(580, 80, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Choose_Folder_Button.sizePolicy().hasHeightForWidth())
        self.Choose_Folder_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Choose_Folder_Button.setFont(font)
        self.Choose_Folder_Button.setMouseTracking(False)
        self.Choose_Folder_Button.setTabletTracking(False)
        self.Choose_Folder_Button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Choose_Folder_Button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Choose_Folder_Button.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    /* background-color: rgb(100, 150, 255); */\n"
"    color: rgb(255, 255, 255);\n"
"    font: 57 10pt \"Rubik Medium\";\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(0, 123, 205);\n"
"}\n"
"\n"
"QPushButton:hover{        \n"
"    background-color: rgb(0, 153, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 85, 110);\n"
"}\n"
"\n"
"/*\n"
"QPushButton:hover{        \n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"*/")
        self.Choose_Folder_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/menu_ico/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Choose_Folder_Button.setIcon(icon2)
        self.Choose_Folder_Button.setIconSize(QtCore.QSize(20, 20))
        self.Choose_Folder_Button.setShortcut("")
        self.Choose_Folder_Button.setCheckable(False)
        self.Choose_Folder_Button.setAutoRepeat(False)
        self.Choose_Folder_Button.setAutoExclusive(False)
        self.Choose_Folder_Button.setObjectName("Choose_Folder_Button")
        self.Info_Video_Label_2 = QtWidgets.QLabel(self.frame)
        self.Info_Video_Label_2.setGeometry(QtCore.QRect(230, 420, 201, 21))
        self.Info_Video_Label_2.setStyleSheet("QLabel{\n"
"    font: 57 12pt \"Rubik Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Info_Video_Label_2.setObjectName("Info_Video_Label_2")
        self.Name_Program_Label_2 = QtWidgets.QLabel(self.frame)
        self.Name_Program_Label_2.setGeometry(QtCore.QRect(40, 379, 581, 31))
        self.Name_Program_Label_2.setStyleSheet("QLabel{\n"
"    font: 57 10pt \"Rubik Medium\";\n"
"    color: rgb(205, 205, 205);\n"
"}")
        self.Name_Program_Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_Program_Label_2.setObjectName("Name_Program_Label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 221, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Name_and_version_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Name_and_version_Layout.setContentsMargins(0, 0, 0, 0)
        self.Name_and_version_Layout.setObjectName("Name_and_version_Layout")
        self.Name_Program_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Name_Program_Label.setStyleSheet("QLabel{\n"
"    font: 57 13pt \"Rubik Medium\";\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Name_Program_Label.setObjectName("Name_Program_Label")
        self.Name_and_version_Layout.addWidget(self.Name_Program_Label)
        self.Version_Program_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Version_Program_Label.setStyleSheet("QLabel{\n"
"    font: 57 13pt \"Rubik Medium\";\n"
"    font-weight: bold;\n"
"    color: rgb(85, 155, 255);\n"
"}")
        self.Version_Program_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Version_Program_Label.setObjectName("Version_Program_Label")
        self.Name_and_version_Layout.addWidget(self.Version_Program_Label)
        self.Progress_Text_Label.raise_()
        self.Info_Video_Label_2.raise_()
        self.Link_Video_LineEdit.raise_()
        self.Check_Video_Button.raise_()
        self.Autor_Program_Label.raise_()
        self.progressBar.raise_()
        self.Roll_MinimizeButton.raise_()
        self.Close_MinimizeButton.raise_()
        self.ButtonsPanel.raise_()
        self.Info_Video_LineEdit.raise_()
        self.Name_Video.raise_()
        self.Video_Info.raise_()
        self.Prew_Label.raise_()
        self.Choose_Folder_Button.raise_()
        self.Name_Program_Label_2.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Link_Video_LineEdit.setPlaceholderText(_translate("MainWindow", "Add link youtube video..."))
        self.Check_Video_Button.setText(_translate("MainWindow", "Find video"))
        self.Autor_Program_Label.setText(_translate("MainWindow", "Program created by Denis Dennisov"))
        self.Progress_Text_Label.setText(_translate("MainWindow", "Download is started..."))
        self.Video_Info.setPlaceholderText(_translate("MainWindow", "Description video..."))
        self.Name_Video.setText(_translate("MainWindow", "Name video..."))
        self.Download_Button.setText(_translate("MainWindow", "Download"))
        self.QualityBox.setCurrentText(_translate("MainWindow", "720p"))
        self.QualityBox.setItemText(0, _translate("MainWindow", "144p"))
        self.QualityBox.setItemText(1, _translate("MainWindow", "240p"))
        self.QualityBox.setItemText(2, _translate("MainWindow", "360p"))
        self.QualityBox.setItemText(3, _translate("MainWindow", "480p"))
        self.QualityBox.setItemText(4, _translate("MainWindow", "720p"))
        self.QualityBox.setItemText(5, _translate("MainWindow", "1080p"))
        self.QualityBox.setItemText(6, _translate("MainWindow", "1440p"))
        self.QualityBox.setItemText(7, _translate("MainWindow", "2160p"))
        self.Info_Video_Label_2.setText(_translate("MainWindow", "Progress download video:"))
        self.Name_Program_Label_2.setText(_translate("MainWindow", "Console messages..."))
        self.Name_Program_Label.setText(_translate("MainWindow", "Video downloader"))
        self.Version_Program_Label.setText(_translate("MainWindow", "v1.0.0"))
import src.icons_app
